paper_path: "1-s2.0-S0022459604000374-main.pdf"

chunk_size: 2000 ## number of characters in each chunk
chunk_overlap: 700 ## overlap between chunks in characters is important for the model to learn the context